### ISSUE TITLE
UI/UX: Bug light/dark mode

### ISSUE THREAD

**Issue by Abilene-may** [mezonai/mezon#1113]
### bug 1:

![Image](https://github.com/nccasia/mezon-fe/assets/107451757/58085f85-77f8-4375-b7ad-c7273df25c9b)
 ### bug 2: Server setting 

![Image](https://github.com/nccasia/mezon-fe/assets/107451757/5b8eae64-9013-442b-bc2a-3e89adf11ff7)

**Comment by Abilene-may** [comment]
in case of Autofill the EVENT NAME @Tungnqs 
and bold the words Cancel and Save

![Image](https://github.com/nccasia/mezon-fe/assets/107451757/fa141875-5c3a-4b7b-9db3-089038459b58)


![Image](https://github.com/nccasia/mezon-fe/assets/107451757/e78c6539-59f2-44d6-a4b4-1c1c38ebbb0e)



![Image](https://github.com/nccasia/mezon-fe/assets/107451757/116fcd2c-b2cf-4c28-a538-c08dd3f4cca7)

**Comment by Abilene-may** [comment]
@Tungnqs màn quản lý Role. Server settings -> Roles 

### bug 1
![Image](https://github.com/nccasia/mezon-fe/assets/107451757/6150ac51-1358-4a08-a509-557b5307b786)

### bug 2
![Image](https://github.com/nccasia/mezon-fe/assets/107451757/5233ce4e-b569-448f-b109-e306999cd48b)

### bug 3
![Image](https://github.com/nccasia/mezon-fe/assets/107451757/cce4d573-f0b1-46df-9306-7bbb9927d03d)

**Comment by Tungnqs** [comment]
done:
bug 1: light mode - Create DM
bug 2: Server setting
bug3: in case of Autofill the EVENT NAME and bold the words Cancel and Save
