### ISSUE TITLE
Mobile App: Interface Error when hashtag the channel

### ISSUE THREAD

**Issue by Abilene-may** [mezonai/mezon#1268]
### Web: 

![Image](https://github.com/nccasia/mezon-fe/assets/107451757/d9e5f373-8ca6-4d9f-86a3-eff62e80dd09)

### Mobile 

![Image](https://github.com/nccasia/mezon-fe/assets/107451757/f5a43257-ab80-44f5-84d4-2980be260d95)

**Comment by phuocnguyenncc** [comment]
@loi-huynhphuc em xem web đổi cơ chế gì update lại nha. a thấy hashtag từ mobile thì work còn từ web thì tạch

**Comment by Abilene-may** [comment]
a @loi-huynhphuc xem hộ e mấy bug này ạ
#### Bug 1: hiển thị sai icon của Voice channel

![Image](https://github.com/nccasia/mezon-fe/assets/107451757/e555d604-598e-423d-9a8a-465d89015838)

#### Bug 2: Lỗi khi edit message với hashtag channel

![Image](https://github.com/nccasia/mezon-fe/assets/107451757/4d8d4b56-41f6-4ece-a781-7441c6b39c0d)

**Comment by Abilene-may** [comment]
### The channel after being deleted will be displayed as *# unknown* instead *# channel_id*

![Image](https://github.com/nccasia/mezon-fe/assets/107451757/2e58dd42-c4bd-4a95-af59-4ebbc77c5f99)

### Discord 

![Image](https://github.com/nccasia/mezon-fe/assets/107451757/bb70f3b8-3b66-4260-b84d-2b9ebc6d13f6)

**Comment by Abilene-may** [comment]
a @loi-huynhphuc Bug 2: Lỗi khi edit message với hashtag channel vẫn còn ạ. 

![Image](https://github.com/nccasia/mezon-fe/assets/107451757/7f0dedfb-2c51-4625-97d2-a71c6e74185f)
