### ISSUE TITLE
UI Error pin message in Channel/Thread/DM

### ISSUE THREAD

**Issue by Cut666** [mezonai/mezon#1306]
### 1. Check permission when removing the Pin message
Only **Admin, manage message role** and **the clan owner** has the permission to create and remove Pin message

### 2. Jump Pin message

**Comment by Abilene-may** [comment]
@Tungnqs 
### Task 1: Add pop up 

![Image](https://github.com/nccasia/mezon-fe/assets/107451757/ea5a9d35-3e0e-4704-8376-20bc54a710e7)

### Task 2: Message notification has been pinned

![Image](https://github.com/nccasia/mezon-fe/assets/107451757/d0a05f4c-820a-4fde-af41-faf7a71bec59)

### Bug: Pin msg with the message is too long 

![Image](https://github.com/user-attachments/assets/3069b80d-4a2a-4e7b-a233-f58c11448a8e)

**Comment by thuy1901** [comment]
![Image](https://github.com/user-attachments/assets/9df22f99-b5da-4ff7-a1a1-8329944062db)



![Image](https://github.com/user-attachments/assets/26b44333-cf5d-4a77-918c-077e60b936ea)

**Comment by Abilene-may** [comment]
### Bug 1: UI Error when executing Pin a message that too long

![Image](https://github.com/user-attachments/assets/50397ef3-7ac6-4149-a62e-b9b39abd5f18)

### Bug 2: UI Error displaying message in the Pin message panel

![Image](https://github.com/user-attachments/assets/15e27a30-955e-4a4a-b4c7-b8c740a7119c)

### Bug 3: UI Error when executing unpin a message

![Image](https://github.com/user-attachments/assets/8f60186c-5d60-4aee-bce1-e1abf8f6197f)

### Bug 4: Light mode

![Image](https://github.com/user-attachments/assets/be7cf87d-054e-49d1-80af-ff1319e850c4)

**Comment by Abilene-may** [comment]
![Image](https://github.com/user-attachments/assets/0085eb5b-2db7-4643-8b4c-c232f6847395)

![Image](https://github.com/user-attachments/assets/7ab0e5f4-6b33-428e-a8cc-9d4fb9ae7920)
