### ISSUE TITLE
Mobile App: UI Error when creating a new thread

### ISSUE THREAD

**Issue by Abilene-may** [mezonai/mezon#1621]
### Bug 1: The Thread name should be displayed in a single line 

![Image](https://github.com/nccasia/mezon-fe/assets/107451757/d64f943f-18ef-4c7b-b605-257464afe96a)

### Bug 2: Don't show all Threads in a channel private when creating a new thread

https://github.com/nccasia/mezon-fe/assets/107451757/37adc96a-9db8-482c-81be-806c75e7d663

**Comment by loi-huynhphuc** [comment]
@Abilene-may  bug 2 e xem thử giúp anh trên web có show đủ ko e
