### ISSUE TITLE
Direct Msg > Can't detect the specific sender

### ISSUE THREAD

**Issue by trucnguyen31** [mezonai/mezon#1637]
Pre-Condition: User has received msg while being logged out before

Steps:

1. Login by using the above account again
2. Go to the DM that user has received the msg as the notification
3. Observe

ER:

AR: Can't detect the specific sender 

![Image](https://github.com/nccasia/mezon-fe/assets/127380920/d6935acf-ab36-4e33-aeea-4657ae1ab6b4)
Note: The msg covered by red border belonged to another user

![Image](https://github.com/nccasia/mezon-fe/assets/127380920/b93cdeea-d54b-4513-b8d1-3ec554aba3c7)

After refreshing, the specific sender is shown
![image](https://github.com/nccasia/mezon-fe/assets/127380920/eb7f150f-4fa1-49ac-b5b1-1e13c331a8b5)

**Comment by phong9xNcc** [comment]
![Image](https://github.com/nccasia/mezon-fe/assets/145142085/443780a2-55ae-41c2-8e59-c44de3aad790)

someone fixed
