### ISSUE TITLE
UI error with Notification badge when @here/@mention in the channel/thread

### ISSUE THREAD

**Issue by Abilene-may** [mezonai/mezon#1656]
### **Bug 2:** Notification badges are not displayed when @here/@mention/reply message are present in the thread

![Image](https://github.com/nccasia/mezon-fe/assets/107451757/8a1b1772-6077-4e5e-ba6a-80353a9f3009)

**Comment by Tran-Binh-Duong** [comment]
@Abilene-may mention @ here don't display notification indicator
