### ISSUE TITLE
Search box does not work when adding members to the channel

### ISSUE THREAD

**Issue by Abilene-may** [mezonai/mezon#1696]
Steps: 
1. click channel settings in channel private 
2. click Permission -> Add members or roles 
3. Enter something in search box 

**ER:** Members and roles similar to those in the search box will be displayed. When starting with @ => only show members

![Image](https://github.com/nccasia/mezon-fe/assets/107451757/f8342b71-1f09-4d71-a612-0fe0c290fbbf)

**Comment by nguyentrannhan** [comment]
search vẫn còn sai

**Comment by Abilene-may** [comment]
### Bug: Search is still case-sensitive

![Image](https://github.com/nccasia/mezon-fe/assets/107451757/a08afae5-bd01-40cb-9efe-7028394be3c3)
