### ISSUE TITLE
DM > UI Error displaying user avatar without image_url

### ISSUE THREAD

**Issue by Abilene-may** [mezonai/mezon#1880]
**ER:** Ava displays the first letter of the user's username

![Image](https://github.com/nccasia/mezon-fe/assets/107451757/8efad765-6828-4c07-ac15-e1698c96b0ea)

**Comment by thuy1901** [comment]
đổi thành chuyển thẳng sang Dm

**Comment by Abilene-may** [comment]
@thuthuy1901 
### Pre-condition: The user don't have avatar 
### description: Avt at position 1 is displayed according to the first letter of the account being logged in.

![Image](https://github.com/user-attachments/assets/2a2f1fa2-ea17-46c2-9ac7-dca456a01db0)
