### ISSUE TITLE
Check that only the (clan owner and who can MANAGE_CLAN) has permission to kick members

### ISSUE THREAD

**Issue by Abilene-may** [mezonai/mezon#2049]
**Pre-condition:** You're a member in a clan and has permission to create a new channel. **It's a private channel and has at least 2 members** 
**Steps:** 
1. Create a new private channel and invite someone 
2. perform the right click in Channel members panel
3. Observe

**ER:** 

![Image](https://github.com/user-attachments/assets/b06ba152-badc-4636-b484-8d0ace725b1f)

**Comment by nguyentrannhan** [comment]
Không được phép kick owner clan

**Comment by Abilene-may** [comment]
@thuthuy1901 Check lại các cases này nha 

**_Note: Don't allow Kicking The Clan Owner_**

Only members with **Admin role** and **the Clan Owner** have the permission to kick members out of the clan. (Admin role also doesn't have permission to kick the Clan owner
