### ISSUE TITLE
Mobile App: Channel mgmt > User profile shows incorrect custom status in the channel/thread

### ISSUE THREAD

**Issue by trucnguyen31** [mezonai/mezon#2229]
## Pre-Condition

- Add custom for at least one user in the channel
- Login successfully by using the account that has been set custom status

![Image](https://github.com/user-attachments/assets/2ca4ce80-3c07-4491-8d20-86e521581124)

## Steps;

1. Go to a channel
2. Tap on the other member username
3. Observe

## ER: The other user profiles must display differrently

- If no status added => dont show anything under the username
- If the account added custom status => show correct content of that account's status

## AR: All the members in the channel shows the same status as the account is logging in

https://github.com/user-attachments/assets/cd44aabd-4d5e-46e8-a5de-925e68a4e913

In channel view:
![Image](https://github.com/user-attachments/assets/96b8e025-821f-4f9c-9161-0ae7588311d7)

In that user's profile view:
![Image](https://github.com/user-attachments/assets/32e6f719-de6a-4c2e-874f-a42c9dc3f292)

**Comment by trucnguyen31** [comment]
Re-style and resize the active status icon
![Image](https://github.com/user-attachments/assets/c2bfe298-8d59-486d-90cd-3d9fcfa62a3b)

**Comment by codengoo** [comment]
@trucnguyen31 không reprocedure được chị ơi

**Comment by trucnguyen31** [comment]
done


![Image](https://github.com/user-attachments/assets/d0b02e95-5e80-4ae2-96a5-ff4e912a7caa)



![Image](https://github.com/user-attachments/assets/45176549-a689-45b3-949f-4d6c7268a436)

**Comment by trucnguyen31** [comment]
done


![Image](https://github.com/user-attachments/assets/d0b02e95-5e80-4ae2-96a5-ff4e912a7caa)



![Image](https://github.com/user-attachments/assets/45176549-a689-45b3-949f-4d6c7268a436)
