### ISSUE TITLE
UI Error when The member list is too long when adding members in role management

### ISSUE THREAD

**Issue by Abilene-may** [mezonai/mezon#2271]
![Image](https://github.com/user-attachments/assets/efa6de0a-1c19-4a19-aba8-4e91ce04c5f8)

### When the member list is too long 

![Image](https://github.com/user-attachments/assets/db4c8993-a37a-4917-9a42-82c413e0c4d3)

**Comment by Abilene-may** [comment]
@thuthuy1901 The scroll is too close and the wrong color in light mode 
The List of members needs to be displayed according to the case below: 
Retrieved according to information in Clan Profile (avatar - Clan Nick Name/Display Name - username), If Clan Profile has not been updated 
=> retrieve according the User Profile
Note: 
1. Name is displayed in order of priority Clan Nick Name > Display Name > username
2. If user don't have avatar => The avatar displayed is the first letter of the username.
Case: The user don't have Clan Nick Name or Display Name => Only Displays username

![Image](https://github.com/user-attachments/assets/2c43bf5e-67ba-49a9-9f75-4e342bf2b30a)

**Comment by thuy1901** [comment]
wait be respond add clan nickName

**Comment by Abilene-may** [comment]
Cannot search by Clan Nick Name
