### ISSUE TITLE
Mobile App: Can't swipe to hide the toast msg sometimes

### ISSUE THREAD

**Issue by trucnguyen31** [mezonai/mezon#2359]
## Steps:

1. Hold on the incoming msg
2. Scroll it downward and then swipe up
3. Move the toast to it's own place as the begining
4. Observe
5. 
## ER: 
The toast msg should disappear

## AR: 
Can't hide the toast msg

https://github.com/user-attachments/assets/e0ef557f-1b96-4823-8e31-e0a2c06cef00

**Comment by codengoo** [comment]
Lỗi ở thư viện phụ thuộc

https://github.com/calintamas/react-native-toast-message/issues/280#issuecomment-991894439

**Comment by trucnguyen31** [comment]
done
