### ISSUE TITLE
the Search members feature isn't optimized when adding members or roles in private channel settings

### ISSUE THREAD

**Issue by Abilene-may** [mezonai/mezon#2361]
### **Clan NickName / Display Name - user name**

**Case:** The user doesn't have Clan Nick Name and Display Name => display only **_username_**

## Bug 2: Allow search in both lowercase and uppercase letters

https://github.com/user-attachments/assets/cc1b481e-992e-4cd2-bd04-8fd9c28c98be

**Comment by thuy1901** [comment]
wait be resopond clan nick name

**Comment by Abilene-may** [comment]
Users without a Display Name are not displayed in the list members when Adding roles and members. @thuthuy1901 
**Expected result:** Users without a Display Name should be displayed in the list members when Adding roles and members.

**Comment by Abilene-may** [comment]
Cannot search by Clan Nick Name
