### ISSUE TITLE
Mobile App: View image > Can't collapse the other sections when viewing an image

### ISSUE THREAD

**Issue by trucnguyen31** [mezonai/mezon#2668]
## Steps:

1. Tap on an image in the DM/Channel msg to have a full view
2. Tap on that image to collapse other sections
3. Observe

## ER
All other sections should be collapsed and only the image will be shown

![Image](https://github.com/user-attachments/assets/a7058a79-59c8-4493-ba9a-4b6f0616dc8f)

## AR
 Can't collapse the other sections when viewing an image

https://github.com/user-attachments/assets/29e9526f-5b92-4c61-82c2-44fd2373f88e

**Comment by phuocnguyenncc** [comment]
@phatphanvan thêm phần này swipe k đc

**Comment by trucnguyen31** [comment]
done
