### ISSUE TITLE
Mobile App: Sometimes button not work when tapping on

### ISSUE THREAD

**Issue by tien-cao** [mezonai/mezon#3189]
**STEPS**
1. Open Clan
2. Tap on Events 
3. Tap on Create button 
4. Select option > Next
5. Check X button & Apply button on Start date & Start time field

**ER**
Button should work smoothly 

**AR**
Sometimes users need to tap on button several times

![Image](https://github.com/user-attachments/assets/195533b6-c069-424d-b1d4-936b5e5ab425)

**Comment by Abilene-may** [comment]
Passed
