### ISSUE TITLE
Mobile app: Lack of message when create a thread

### ISSUE THREAD

**Issue by tien-cao** [mezonai/mezon#3346]
> **STEPS**
1. Hold a channel 
2. Tap on Threads option
3. Tap on + button
4. Create a thead success 
5. Observe new thread & list thread of channel

> **ER**
Display 1st message in thread
Thread display in thread list of channel

![Image](https://github.com/user-attachments/assets/e1174159-1a28-405a-961f-d69b3cc77ac0)

> **AR**
NOT display 1st message in thread
Thread NOT display in thread list of channel

https://github.com/user-attachments/assets/90192f4b-e568-4009-8d92-7ff05aeb613c

![Image](https://github.com/user-attachments/assets/6bc72b43-b156-47d9-a1e4-2faa8be19308)

![Image](https://github.com/user-attachments/assets/bb4af782-e8d1-4f41-b4ee-98f5a0a81ff1)

**Comment by Abilene-may** [comment]
**Environment:** Mobile - TF version 27 
**Pre-condition:** Successfully logged in to Mezon

## Bug 1: There is no action to create a new Thread within a Thread

![Image](https://github.com/user-attachments/assets/096277b4-8aa4-4328-8d9a-387fef577870)

## Bug 2:  Wrong icon Thread with a private Thread 

![Image](https://github.com/user-attachments/assets/623fdb82-7eb2-4bfd-898c-cdb021d2f950)

**Comment by tien-cao** [comment]
### **FAILED**

1. View thread list > Not display last message of thread 

![Image](https://github.com/user-attachments/assets/4e707895-e321-4fd7-9cac-9cb9252bc607)

2. Still display wrong icon of private thread

**Comment by Abilene-may** [comment]
**Environment:** Mobile - IOS - TF version 1.0.70 (2) 

Passed
