### ISSUE TITLE
Ctrl+K to search channel > Join channel > Joined channel should display at the middle of the left side bar

### ISSUE THREAD

**Issue by tien-cao** [mezonai/mezon#3361]
> **STEPS**
1. In Clan
2. Use Ctrl+K on keyboard
3. Input channel name
4. Enter 
5. Observe left side bar 

> **ER**
The joined channel should display at the middle of the left side bar 
![Image](https://github.com/user-attachments/assets/810b88aa-e176-478c-a035-4347ace97c6a)

> **AR**

https://github.com/user-attachments/assets/d0c80c12-6329-4e23-a371-2788141d272a

**Comment by Abilene-may** [comment]
passed
