### ISSUE TITLE
Wrong display when sending hyperlink

### ISSUE THREAD

**Issue by tien-cao** [mezonai/mezon#3373]
> ### **STEPS**
1. In a Channel/ Thread/ DM message 
2. Send a hyper link 
3. Observe

> ### **ER**
Display hyperlink format correctly

> ### **AR**

https://github.com/user-attachments/assets/63dda7ce-236e-4fa9-bc72-ce179da2950a

![Image](https://github.com/user-attachments/assets/d66850ae-9c24-45b1-a1f1-0aa8029f29ec)

**Comment by Abilene-may** [comment]
Markdown has been dropped => Not a bug
