### ISSUE TITLE
Mobile App: Some UI bugs when setting Light mode

### ISSUE THREAD

**Issue by tien-cao** [mezonai/mezon#3415]
> ### **BUG 1 Event list**
![Image](https://github.com/user-attachments/assets/5e884081-c05e-4a74-bf95-f80eef3c65f8)

> ### **BUG 2 Lack of collapse icon**
### **ER**
![Image](https://github.com/user-attachments/assets/d0ba8d96-a5e4-4991-a1fb-5608962ea88f)

### **AR**
https://github.com/user-attachments/assets/56d3bdae-5d63-4fdc-bfcd-d312e0455d3a

> ### ** BUG 3 Attach file**
### **ER**
![Image](https://github.com/user-attachments/assets/8b805a85-ed19-4891-bb22-dc352d347e98)

### **AR**
![Image](https://github.com/user-attachments/assets/edf953b5-3b49-4c03-b3d5-79d3926a53dc)

> ### **BUG 4 Icon color when switch to dark/ light mode**

https://github.com/user-attachments/assets/10defb39-f2f3-4523-8008-258499ea88ec

**Comment by Abilene-may** [comment]
Passed
