### ISSUE TITLE
Mobile app: Should expand compose message field if user type/paste long text

### ISSUE THREAD

**Issue by tien-cao** [mezonai/mezon#3457]
> ### **ER**
- Message in row 3 -> Expand compose message
- Message from row 4... -> Display scroll 

> ### **AR**

https://github.com/user-attachments/assets/4b13281d-b373-48fa-a4b1-bbf87189c532

**Comment by Abilene-may** [comment]
Passed 
**Environment:** Mobile - IOS - TF version 1.0.62(2) 

![Image](https://github.com/user-attachments/assets/d77dd455-2a0b-42ff-9f2d-2f5154f84988)
