### ISSUE TITLE
Display wrong role in Clan

### ISSUE THREAD

**Issue by tien-cao** [mezonai/mezon#3558]
> ### **STEPS**
1. Open desktop app
2. Open Clan 1 
3. Clan settings > Roles 
4. Open Clan 2, 3, 4 >  Open Clan settings > Roles 
5. Observe 

> ### **ER**
Should display roles which were created in that clan 

> ### **AR**
Disply roles in Clan 1 for every clan 

https://github.com/user-attachments/assets/246a7b5d-2552-404b-8fa6-5259be1f3a40

**Comment by Abilene-may** [comment]
passed
