### ISSUE TITLE
Create popup short user profile when click to username.

### ISSUE THREAD

**Issue by nguyentrannhan** [mezonai/mezon#424]
![Image](https://github.com/nccasia/mezon-fe/assets/17939754/e465224a-173f-4ff7-a181-c8a23070a668)

**Comment by Cut666** [comment]
channel public
        WITH clan_users, role_clan tạo 2 bảng lấy danh sách user trong clan và role từ user_role
        kết hợp 2 bảng để lấy được ARRAY_AGG(ur.role_id) cho từng user
      vì channel public không add role vào channel
channel private
      kết hợp 2 SELECT  thông qua UNION ALL
      SELECT 1: lấy ARRAY_AGG(ur.role_id) AS role_ids từ bảng user_role where role.active = 1
      SELECT 1: lấy ARRAY_AGG(ur.role_id) AS role_ids từ bảng role_channel where role_channel.active = 1
